Repository AndreasReitberger/RestApiClientSharp, pull requests merged in 2025-03, with the labels that each got.

#37 Fix missing error messages
  src/RestApiClientSharp/RestApiClient.Proxy.cs
Labels: enhancement, test

#36 Update dotnet_unittest.yml
  .github/workflows/dotnet_unittest.yml
Labels: test

#38 Fix missing error message
  src/RestApiClientSharp/RestApiClient.Rest.cs
Labels: bug
